export const FETCH_LINK_TOKEN = "FETCH_LINK_TOKEN";
export const LINK_LOADING = "LINK_LOADING";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const ACCOUNTS_LOADING = "ACCOUNTS_LOADING";
export const GET_BALANCES = "GET_BALANCES";
export const BALANCES_LOADING = "BALANCES_LOADING"
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const TRANSACTIONS_LOADING = "TRANSACTIONS_LOADING";

export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";